In [ ]:
#Handling structured data (like Excel tables)
#Series (Like single cloloum)
#DataFrame(coloum+row)

In [5]:
#Creating series
import pandas
import pandas as pd
n= pd.Series([10,20,30,40,50])
print(n)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
#customize index
x=pd.Series([10,20],index=['a','b'])
print(x)

a    10
b    20
dtype: int64

In [7]:
#Creating Dataframe
data={
    "Name":["Sridhar","Prathima","Amrutha"],
    "Age":[50,32,23],
    "Salary":[100000,20000,15000]
}
print(pd.DataFrame(data))

       Name  Age  Salary
0   Sridhar   50  100000
1  Prathima   32   20000
2   Amrutha   23   15000

In [8]:
#methods
#info(coloum type)
df = pd.DataFrame(data)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None

In [10]:
#describe    #give statistics
print(df.describe())

             Age         Salary
count   3.000000       3.000000
mean   35.000000   45000.000000
std    13.747727   47696.960071
min    23.000000   15000.000000
25%    27.500000   17500.000000
50%    32.000000   20000.000000
75%    41.000000   60000.000000
max    50.000000  100000.000000

In [22]:
#head #give first 5 rows
school={
    "Kannada":[90,85,88,2,2,4],
    "English":[85,90,77,88,66,44],
    "Hindi":[80,89,33,90,66,78],
    "Science":[70,88,99,45,66,77]

    }
p=(pd.DataFrame(school))
print(p.head())

   Kannada  English  Hindi  Science
0       90       85     80       70
1       85       90     89       88
2       88       77     33       99
3        2       88     90       45
4        2       66     66       66

In [23]:
print(p.shape)

(6, 4)

In [24]:
#Selecting data
#select coloum
p["Kannada"]

0    90
1    85
2    88
3     2
4     2
5     4
Name: Kannada, dtype: int64

In [31]:
#selecting multiple coloum
p[["English","Hindi","Science"]]

   English  Hindi  Science
0       85     80       70
1       90     89       88
2       77     33       99
3       88     90       45
4       66     66       66
5       44     78       77

In [35]:
#iloc it works postion(numbers)
p.iloc[1]

Kannada    85
English    90
Hindi      89
Science    88
Name: 1, dtype: int64

In [40]:
#selcting row using index
#loc it works on label and number
z=pd.DataFrame(school,index=["a","b","c","d","e","f"])
print(z)

   Kannada  English  Hindi  Science
a       90       85     80       70
b       85       90     89       88
c       88       77     33       99
d        2       88     90       45
e        2       66     66       66
f        4       44     78       77

In [42]:
#using loc
z.loc['d']

Kannada     2
English    88
Hindi      90
Science    45
Name: d, dtype: int64

In [44]:
#using iloc
z.iloc["d"]  #give error because using only postional arguments

TypeError: Cannot index by location index with a non-integer key

In [52]:
#Filtering Data
import pandas as pd

data = {
    "Name": ["Rahul", "Sneha", "Arjun", "Meera", "Kiran", "Anjali"],
    "Age": [25, 28, 24, 30, 27, 26],
    "Salary": [35000, 42000, 30000, 50000, 38000, 41000],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Finance"]
}

df = pd.DataFrame(data)

print(df)

     Name  Age  Salary Department
0   Rahul   25   35000         HR
1   Sneha   28   42000         IT
2   Arjun   24   30000    Finance
3   Meera   30   50000         IT
4   Kiran   27   38000         HR
5  Anjali   26   41000    Finance

In [51]:

df[df["Age"]>25]

     Name  Age  Salary Department
1   Sneha   28   42000         IT
3   Meera   30   50000         IT
4   Kiran   27   38000         HR
5  Anjali   26   41000    Finance

In [53]:
#fliterning more than one Data
df[(df["Age"]>23) & (df["Salary"]>38000)]

     Name  Age  Salary Department
1   Sneha   28   42000         IT
3   Meera   30   50000         IT
5  Anjali   26   41000    Finance

In [55]:
#Adding new coloum
df["Bonus"]=df["Salary"]*0.10
print(df)

     Name  Age  Salary Department   Bonus
0   Rahul   25   35000         HR  3500.0
1   Sneha   28   42000         IT  4200.0
2   Arjun   24   30000    Finance  3000.0
3   Meera   30   50000         IT  5000.0
4   Kiran   27   38000         HR  3800.0
5  Anjali   26   41000    Finance  4100.0

In [57]:
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Arun", "Meena", "John", "Priya", "Ravi", "Sara"],
    "Department": ["HR", "IT", "IT", "Finance", None, "HR"],
    "Age": [25, 28, None, 32, 30, None],
    "Salary": [30000, 45000, 40000, None, 38000, 42000],
    "Experience_Years": [2, 5, 3, 7, None, 4]
}

df = pd.DataFrame(data)

print(df)

   Employee_ID   Name Department   Age   Salary  Experience_Years
0          101   Arun         HR  25.0  30000.0               2.0
1          102  Meena         IT  28.0  45000.0               5.0
2          103   John         IT   NaN  40000.0               3.0
3          104  Priya    Finance  32.0      NaN               7.0
4          105   Ravi       None  30.0  38000.0               NaN
5          106   Sara         HR   NaN  42000.0               4.0

In [63]:
#handling missing values
#is null if value is missing True or False(if value is present)

df.isnull()

   Employee_ID   Name  Department    Age  Salary  Experience_Years
0        False  False       False  False   False             False
1        False  False       False  False   False             False
2        False  False       False   True   False             False
3        False  False       False  False    True             False
4        False  False        True  False   False              True
5        False  False       False   True   False             False

In [60]:
#df.isnull().sum()
#it will give sum of null value in coloum
df.isnull().sum()

Employee_ID         0
Name                0
Department          1
Age                 2
Salary              1
Experience_Years    1
dtype: int64

In [61]:
#df.dropna()
#remove the rows contains missing value
df.dropna()

   Employee_ID   Name Department   Age   Salary  Experience_Years
0          101   Arun         HR  25.0  30000.0               2.0
1          102  Meena         IT  28.0  45000.0               5.0

In [65]:
#df.fillna()
df.fillna("a")

   Employee_ID   Name Department   Age   Salary Experience_Years
0          101   Arun         HR  25.0  30000.0              2.0
1          102  Meena         IT  28.0  45000.0              5.0
2          103   John         IT     a  40000.0              3.0
3          104  Priya    Finance  32.0        a              7.0
4          105   Ravi          a  30.0  38000.0                a
5          106   Sara         HR     a  42000.0              4.0

In [68]:
df.describe()

       Employee_ID        Age        Salary  Experience_Years
count     6.000000   4.000000      5.000000          5.000000
mean    103.500000  28.750000  39000.000000          4.200000
std       1.870829   2.986079   5656.854249          1.923538
min     101.000000  25.000000  30000.000000          2.000000
25%     102.250000  27.250000  38000.000000          3.000000
50%     103.500000  29.000000  40000.000000          4.000000
75%     104.750000  30.500000  42000.000000          5.000000
max     106.000000  32.000000  45000.000000          7.000000

In [69]:
#by using fillna i can also fill mean and median value
df["Age"].fillna(df["Age"].mean())

0    25.00
1    28.00
2    28.75
3    32.00
4    30.00
5    28.75
Name: Age, dtype: float64

In [71]:
# Fill Median
df["Salary"].fillna(df["Salary"].median())

0    30000.0
1    45000.0
2    40000.0
3    40000.0
4    38000.0
5    42000.0
Name: Salary, dtype: float64

In [72]:
#forward fillng
df.fillna(method="ffill")

/tmp/ipykernel_299/674185041.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

   Employee_ID   Name Department   Age   Salary  Experience_Years
0          101   Arun         HR  25.0  30000.0               2.0
1          102  Meena         IT  28.0  45000.0               5.0
2          103   John         IT  28.0  40000.0               3.0
3          104  Priya    Finance  32.0  40000.0               7.0
4          105   Ravi    Finance  30.0  38000.0               7.0
5          106   Sara         HR  30.0  42000.0               4.0

In [73]:
#backward filling
df.fillna(method="bfill")

/tmp/ipykernel_299/3375846734.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="bfill")

   Employee_ID   Name Department   Age   Salary  Experience_Years
0          101   Arun         HR  25.0  30000.0               2.0
1          102  Meena         IT  28.0  45000.0               5.0
2          103   John         IT  32.0  40000.0               3.0
3          104  Priya    Finance  32.0  38000.0               7.0
4          105   Ravi         HR  30.0  38000.0               4.0
5          106   Sara         HR   NaN  42000.0               4.0

In [75]:
#group by
df.groupby("Age")["Salary"].mean()

Age
25.0    30000.0
28.0    45000.0
30.0    38000.0
32.0        NaN
Name: Salary, dtype: float64

In [77]:
#Sorting
df.sort_valuesm("Age")

   Employee_ID   Name Department   Age   Salary  Experience_Years
0          101   Arun         HR  25.0  30000.0               2.0
1          102  Meena         IT  28.0  45000.0               5.0
4          105   Ravi       None  30.0  38000.0               NaN
3          104  Priya    Finance  32.0      NaN               7.0
2          103   John         IT   NaN  40000.0               3.0
5          106   Sara         HR   NaN  42000.0               4.0