In [ ]:
#Given sample list,tuple,set from elements from 1 to 10convert into pada sereis
#create saparete list of panda sereis

In [ ]:
import pandas as pd
ind=['a','b','c','d','e','f','g','h','i', 'j'] # Added 'j' to match the data length
s=pd.Series([1,2,3,4,5,6,7,8,9,10],index=ind)
print(s)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
print(pd.Series((1,2,3,4,5,6,7,8,9)))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
print(pd.Series{1,2,3,4,5,6,7,8,9})
#we cannot convert set  directly into sereis

TypeError: 'set' type is unordered

In [ ]:
print(pd.Series(list({1,2,3,4,5,6,7,8,9,10}), index=ind))

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int64

In [ ]:
#create dic with 3 key value convert as Sereis
dic={
    "Name":["Varshi","Hasini"],
    "Age":[20,21],
    "Marks":[100,100]
}
print(pd.Series(dic))
#key are index value

Name     [Varshi, Hasini]
Age              [20, 21]
Marks          [100, 100]
dtype: object

In [ ]:
#create pandas series with element from 0 to 5
#convert back to list ,tuple and set
nu=[1,2,3,4,5]
ind=[0,1,2,3,4]
d=pd.Series(nu,index=ind)
print(d)
print(list(d))
print(tuple(d))
print(set(d)) #We can covert Sereies into list but not vice-versa

0    1
1    2
2    3
3    4
4    5
dtype: int64
[1, 2, 3, 4, 5]
(1, 2, 3, 4, 5)
{1, 2, 3, 4, 5}

In [ ]:
#create sample pandas with x integer element
#print 1st element
#1st 5 element
#insert 50 at index 5
#udpate last element in the series with value 100
#delete 1st elements

In [ ]:
nu=[1,2,3,4,5,6,7]
v=(pd.Series(nu))
print(v)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:
print(v[0])

1

In [ ]:
print(v.head())

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
#last 5
print(v.tail())

2    3
3    4
4    5
5    6
6    7
dtype: int64

In [ ]:

#update element at 5
v[5]=200
print(v)

0      1
1      2
2      3
3      4
4      5
5    200
6      9
dtype: int64

In [ ]:
#update last elment 9
v[6]=9
print(v)

0      1
1      2
2      3
3      4
4      5
5    200
6      9
dtype: int64

In [ ]:
print(v.drop(6))

0      1
1      2
2      3
3      4
4      5
5    200
dtype: int64

In [ ]:
#concate two sereies
s1=pd.Series([1,2,3])
s2=pd.Series([4,5,6])
new=pd.concat([s1,s2])
print(new)

0    1
1    2
2    3
0    4
1    5
2    6
dtype: int64

In [ ]:
#create dataframes [name and age]
#print 3 rows having dataframe
#print age>15
#update last row name and age

In [2]:
import pandas as pd
dic={
    "name":['varsh','Ammu','sri','Prathu'],
    "Age":[12,23,34,45]}
x=pd.DataFrame(dic)
print(x)

     name  Age
0   varsh   12
1    Ammu   23
2     sri   34
3  Prathu   45

In [3]:
print(x[:3]) #or print(x.head(3))

    name  Age
0  varsh   12
1   Ammu   23
2    sri   34

In [7]:
x[x["Age"]>25]

     name  Age
2     sri   34
3  Prathu   45

In [10]:
dic["name"]=["Prathu","Amma"]
print(dic)

{'name': ['Prathu', 'Amma'], 'Age': [12, 23, 34, 45], 'Prathu': 'Amma'}

In [11]:
dic1={
    "name":['qqq','mmm','saa','Pppu'],
    "Age":[11,33,14,64]}
x1=pd.DataFrame(dic1)
print(x1)

   name  Age
0   qqq   11
1   mmm   33
2   saa   14
3  Pppu   64

In [15]:
#concate
p=pd.concat([x,x1],ignore_index=True)
print(p)

     name  Age
0   varsh   12
1    Ammu   23
2     sri   34
3  Prathu   45
4     qqq   11
5     mmm   33
6     saa   14
7    Pppu   64

In [18]:
p.loc[4,"name"]="Jhon"
p.loc[4,"Age"]=24
print(p)

     name  Age
0   varsh   12
1    Ammu   23
2     sri   34
3  Prathu   45
4    Jhon   24
5     mmm   33
6     saa   14
7    Pppu   64

In [20]:
#delete 1st row
pr=(p.drop(0))
print(pr)

     name  Age
1    Ammu   23
2     sri   34
3  Prathu   45
4    Jhon   24
5     mmm   33
6     saa   14
7    Pppu   64

In [ ]:
#create DataFrame(name,age)
#Search name where age is 20
#sort ascending order in terms of age

In [15]:
import pandas as pd
import numpy as np

data = {
    "Employee_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Arun", "Meena", "John", "Priya", "Ravi", "Sara"],
    "Department": ["HR", "IT", "IT", "Finance", "HR", "HR"],
    "Age": [25, 28, 21, 32, 30, 21],
    "Salary": [30000, 45000, 40000,2000, 38000, 42000],
    "Experience_Years": [2, 5, 3, 7, 2, 4]
}

df = pd.DataFrame(data)

print(df)

   Employee_ID   Name Department  Age  Salary  Experience_Years
0          101   Arun         HR   25   30000                 2
1          102  Meena         IT   28   45000                 5
2          103   John         IT   21   40000                 3
3          104  Priya    Finance   32    2000                 7
4          105   Ravi         HR   30   38000                 2
5          106   Sara         HR   21   42000                 4

In [26]:
print(df.loc[df['Age']>25, 'Name'])

1    Meena
3    Priya
4     Ravi
Name: Name, dtype: object

In [5]:
print(sorted(df["Age"]))

[21, 21, 25, 28, 30, 32]

In [10]:
#If u want to sort age with name also then
df = df.sort_values(by='Age')
df

   Employee_ID   Name Department  Age  Salary  Experience_Years
2          103   John         IT   21   40000                 3
5          106   Sara         HR   21   42000                 4
0          101   Arun         HR   25   30000                 2
1          102  Meena         IT   28   45000                 5
4          105   Ravi         HR   30   38000                 2
3          104  Priya    Finance   32    2000                 7

In [17]:
#Using for loop print ge and and store in set
se = set()
lis=[]
for i in df['Age']:
  print(i)
  se.add(i)
  lis.append(i)
print(se)
print(lis)

25
28
21
32
30
21
{32, 21, 25, 28, 30}
[25, 28, 21, 32, 30, 21]

In [9]:
#titanic dataset
import seaborn as s
import numpy as np
data=s.load_dataset("titanic")
print(data)

     survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third
1           1       1  female  38.0      1      0  71.2833        C   First
2           1       3  female  26.0      0      0   7.9250        S   Third
3           1       1  female  35.0      1      0  53.1000        S   First
4           0       3    male  35.0      0      0   8.0500        S   Third
..        ...     ...     ...   ...    ...    ...      ...      ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second
887         1       1  female  19.0      0      0  30.0000        S   First
888         0       3  female   NaN      1      2  23.4500        S   Third
889         1       1    male  26.0      0      0  30.0000        C   First
890         0       3    male  32.0      0      0   7.7500        Q   Third

       who  adult_male deck  embark_town alive  alone
0      man        True  NaN  Southampton    no  False
1    woman       False    C    Cherbourg   yes  False
2    woman       False  NaN  Southampton   yes   True
3    woman       False    C  Southampton   yes  False
4      man        True  NaN  Southampton    no   True
..     ...         ...  ...          ...   ...    ...
886    man        True  NaN  Southampton    no   True
887  woman       False    B  Southampton   yes   True
888  woman       False  NaN  Southampton    no  False
889    man        True    C    Cherbourg   yes   True
890    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [23]:
data.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [27]:
#Find all feamale passenger
data[data["sex"]=="female"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [26]:
#how many total passenger in data set
len(data)

891

In [4]:
#find average age all passenger
data["age"].mean()

np.float64(29.69911764705882)

In [5]:
#find the youongest
data["age"].min()

0.42

In [6]:
#oldest person
data["age"].max()

80.0

In [11]:
#find how many person in class 1 ,2,3
data["pclass"].value_counts()[1]

np.int64(216)